name: Build & Deploy website

on:
  push:
    branches: 
      - main

jobs: 
  build-deploy:
    name: Build and Deploy website coding verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the website
        run: | 
          mvn clean
          mvn -B package --file pom.xml

  ServiceNowDevOpsChange:
    # jobs that must complete successfully before this job will run
    needs: build-deploy
    # type of machine to run the job on
    runs-on: ubuntu-latest
    name: 'ServiceNow DevOps Change'
    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v3.0.0
        with:
          # Devops Integration Token
          devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
          # ServiceNow Instance URL
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          # Orchestration Tool Id
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          # GitHub Context
          context-github: ${{ toJSON(github) }}
          # Display Name of the Job
          job-name: 'ServiceNow DevOps Change'
          change-request: '{"setCloseCode":"true","autoCloseChange":true,"attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"27af301c0f649640bcf30eece1050eb0","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed","chg_model":"${{ secrets.SN_DEVOPS_CHANGE_MODEL }}","u_region":"${{ secrets.SN_DEVOPS_CHANGE_REGION }}","business_service":"${{ secrets.SN_DEVOPS_CHANGE_SERVICE }}","service_offering":"${{ secrets.SN_DEVOPS_CHANGE_OFFERING }}","cmdb_ci":"${{ secrets.SN_DEVOPS_CHANGE_CI }}"}}'
